[package]
name = "qoi-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.qoi]
path = ".."

[[bin]]
name = "pixel_mapping"
path = "fuzz_targets/pixel_mapping.rs"
test = false
doc = false
bench = false
